language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t injetis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true injetis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-006765569788"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

